services:
  python-terminal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: chip-8-python
    stdin_open: true
    tty: true
    volumes:
      - .:/code
